// cli/hotkey/hud_window.swift
// Native macOS Hardware Notch Dynamic Island & Floating Capsule HUD for Pet-Talk.
//
// Technical Architecture & Specifications:
// - Hardware Notch Awareness: Queries NSScreen auxiliaryTopLeftArea / auxiliaryTopRightArea
//   to MEASURE the physical MacBook webcam notch at runtime (never a hardcoded size).
//   No notch reported (external display, iMac, older MacBook) -> 180 pt fallback pill.
// - Hardware-Software Fusion:
//   - Top edge anchors flush to screen.frame.maxY, enveloping the camera notch in pure #000000.
//   - Continuous squircle curvature (r=20px) on bottom corners.
//   - Concave top ear fillets (r=10px) that sweep outward smoothly into the display bezel.
// - Motion Design Language (Apple Fluid Springs):
//   - "The Drip" Entrance: Unfolds downward from the physical notch (38pt -> 52pt) under a real
//     damped spring (HUDSpringDriver for the window frame, CASpringAnimation for layer opacity).
//   - Dynamic Expansion: Morphs from the measured notch to 440pt, height 52pt -> 60pt, same spring.
//   - "Suction" Retraction: Springs back up into the physical camera notch on dismissal.
// - Fallback for External Displays: Gracefully falls back to an elegant floating pill (r=22px) centered at top.
// - Non-activating NSPanel subclass: [.nonactivatingPanel, .borderless] (zero focus stealing).
// - Level: .floating, Spaces: [.canJoinAllSpaces, .fullScreenAuxiliary], Click-through: ignoresMouseEvents = true.

import AppKit
import Foundation
import QuartzCore

// MARK: - HUDTokens
//
// The live spring/geometry/gesture values the HUD runs on. Two layers, no third:
//
//   1. DEFAULTS come from cli/hotkey/DesignTokens.swift — generated by
//      design/build.py from design/tokens.pet-talk.json (the design lane owns
//      both). No number below is typed twice; where DesignTokens has no
//      equivalent (the ear-fillet threshold, the pill radius, the double-tap
//      window) the value is pet-talk's own and lives here.
//   2. OVERRIDES come from ~/.pet-talk/config.yaml (`motion:` / `geometry:` /
//      `hotkey:`, see config.swift), applied at launch by HUDTokens.apply(from:),
//      so a design-playground export lands without a rebuild.
//
// Everything is a `static var` for exactly that reason.
public struct HUDTokens {
    // Damped-spring physics. These three are the ONLY source of spring numbers:
    // HUDSpring.animation() and HUDSpringDriver both read them.
    public static var springStiffness: Double = DesignTokens.springStiffness
    public static var springDamping: Double = DesignTokens.springDamping
    public static var springMass: Double = DesignTokens.springMass

    // Geometry. capsuleWidth itself is measured from the screen, never stored.
    public static var fallbackCapsuleWidth: CGFloat = CGFloat(DesignTokens.capsuleWidthRest)
    public static var expandedWidth: CGFloat = CGFloat(DesignTokens.capsuleWidthExpanded)
    /// pet-talk's own: how far content must spill past the notch before ears appear.
    public static var earFilletThreshold: CGFloat = 24.0
    public static var earFilletRadius: CGFloat = CGFloat(DesignTokens.radiusEarFillet)
    public static var bottomCornerRadius: CGFloat = CGFloat(DesignTokens.radiusBottom)
    /// pet-talk's own: the no-notch floating pill is rounder than the island.
    public static var pillCornerRadius: CGFloat = 22.0

    // Gesture (pet-talk's own: the pause window)
    public static var doubleTapWindowMs: Double = 400.0

    /// Apply a config.yaml override. Unset keys keep the built-in default.
    public static func apply(from config: PetTalkConfig) {
        if let v = config.motion.springStiffness { springStiffness = v }
        if let v = config.motion.springDamping { springDamping = v }
        if let v = config.motion.springMass { springMass = v }
        if let v = config.geometry.notchWidthFallback { fallbackCapsuleWidth = v }
        if let v = config.geometry.expandedWidth { expandedWidth = v }
        if let v = config.geometry.earFilletThreshold { earFilletThreshold = v }
        if let v = config.geometry.earFilletRadius { earFilletRadius = v }
        if let v = config.geometry.bottomCornerRadius { bottomCornerRadius = v }
        if let v = config.geometry.pillCornerRadius { pillCornerRadius = v }
        if let v = config.hotkey.doubleTapWindowMs { doubleTapWindowMs = v }
    }
}

// MARK: - Spring: the one CASpringAnimation factory

public enum HUDSpring {
    /// The single place a CASpringAnimation is constructed. Its physics read the
    /// three declared tokens; a literal here would be the bug this replaced.
    public static func animation(keyPath: String, from: Any?, to: Any?) -> CASpringAnimation {
        let spring = CASpringAnimation(keyPath: keyPath)
        spring.mass = CGFloat(HUDTokens.springMass)
        spring.stiffness = CGFloat(HUDTokens.springStiffness)
        spring.damping = CGFloat(HUDTokens.springDamping)
        spring.initialVelocity = 0.0
        spring.fromValue = from
        spring.toValue = to
        spring.duration = spring.settlingDuration
        spring.fillMode = .both
        spring.isRemovedOnCompletion = true
        return spring
    }

    /// Settling time of the declared spring, in seconds.
    public static var settlingDuration: Double {
        Double(animation(keyPath: "opacity", from: 0.0, to: 1.0).settlingDuration)
    }
}

// MARK: - Spring driver (window frame)

/// A CASpringAnimation cannot drive an NSWindow's frame, and the HUD *is* a
/// window — so window geometry is integrated here from the SAME three tokens:
/// semi-implicit Euler on a = (-k*x - c*v) / m, stepped at 120 Hz, reporting a
/// normalized 0 -> 1 progress (overshoot included) that the caller lerps its
/// geometry along.
public final class HUDSpringDriver {
    private let stiffness: Double
    private let damping: Double
    private let mass: Double
    private let onStep: (Double) -> Void
    private let onDone: () -> Void
    private let stepSeconds: Double = 1.0 / 120.0
    private let timeoutSeconds: Double

    private var position: Double = 0.0
    private var velocity: Double = 0.0
    private var elapsed: Double = 0.0
    private var timer: Timer?

    public init(
        stiffness: Double = HUDTokens.springStiffness,
        damping: Double = HUDTokens.springDamping,
        mass: Double = HUDTokens.springMass,
        timeoutSeconds: Double = 1.5,
        onStep: @escaping (Double) -> Void,
        onDone: @escaping () -> Void
    ) {
        self.stiffness = stiffness
        self.damping = damping
        self.mass = mass
        self.timeoutSeconds = timeoutSeconds
        self.onStep = onStep
        self.onDone = onDone
    }

    public var isRunning: Bool { timer != nil }

    public func start() {
        cancel()
        position = 0.0
        velocity = 0.0
        elapsed = 0.0
        onStep(0.0)
        let t = Timer(timeInterval: stepSeconds, repeats: true) { [weak self] _ in
            self?.tick()
        }
        timer = t
        // .common so the spring keeps stepping while a menu or drag tracks.
        RunLoop.main.add(t, forMode: .common)
    }

    private func tick() {
        elapsed += stepSeconds
        let displacement = position - 1.0
        let acceleration = (-stiffness * displacement - damping * velocity) / max(0.0001, mass)
        velocity += acceleration * stepSeconds
        position += velocity * stepSeconds

        // Sub-pixel: 0.004 of a 14pt travel is 0.06pt, so the tail below this is
        // invisible and holding the timer open for it only burns CPU.
        let settled = abs(position - 1.0) < 0.004 && abs(velocity) < 0.05
        if settled || elapsed >= timeoutSeconds {
            position = 1.0
            velocity = 0.0
            onStep(1.0)
            cancel()
            onDone()
            return
        }
        onStep(max(0.0, position))
    }

    public func cancel() {
        timer?.invalidate()
        timer = nil
    }
}

// MARK: - Motion Design Language & Timing Tokens

public struct HUDMotionTokens {
    // The three spring numbers live in HUDTokens (config-overridable); these are
    // re-exported so the debug dump and older call sites keep one spelling.
    public static var springStiffness: Double { HUDTokens.springStiffness }
    public static var springDamping: Double { HUDTokens.springDamping }
    public static var springMass: Double { HUDTokens.springMass }
    public static let dripDuration: Double = 0.22 // 220ms
    public static let blossomDuration: Double = 0.24 // 240ms
    public static let stateTransitionDuration: Double = 0.16 // 160ms
    public static let suctionRetractionDuration: Double = DesignTokens.durationSleepRetract / 1000.0
    public static let errorShakeDuration: Double = DesignTokens.errorShakeDuration / 1000.0
    public static let errorShakeAmplitude: Double = DesignTokens.errorShakeAmplitude
    public static let errorShakeCycles: Int = Int(DesignTokens.errorShakeCycles)
    public static let reduceMotionDuration: Double = DesignTokens.reducedMotionCrossfade / 1000.0
    /// Budget only. The Escape/barge path is a HARD CUT (no animation at all),
    /// so nothing consumes this as a duration — it is the ceiling that path is
    /// measured against.
    public static let escapeDismissBudget: Double = DesignTokens.durationEscapeDismiss / 1000.0

    public static let blossomTimingFunction = CAMediaTimingFunction(controlPoints: 0.22, 1.0, 0.36, 1.0)
    public static let stateTransitionTimingFunction = CAMediaTimingFunction(name: .easeOut)
    public static let suctionRetractionTimingFunction = CAMediaTimingFunction(name: .easeIn)
}

public typealias AppleMotionTokens = HUDMotionTokens

// MARK: - Notch Geometry & Manager

public struct NotchGeometry {
    public let hasNotch: Bool
    public let rect: NSRect          // Notch rectangle in screen coordinates
    public let notchWidth: CGFloat   // Measured: right.minX - left.maxX
    public let notchHeight: CGFloat  // Measured: auxiliary area height (38 pt typical)
    public let screenFrame: NSRect
    public let visibleFrame: NSRect
}

public class NotchManager {
    public static let shared = NotchManager()

    public func currentNotch(for screen: NSScreen? = nil) -> NotchGeometry {
        let targetScreen = screen ?? NSScreen.main ?? (NSScreen.screens.first ?? NSScreen())
        let sFrame = targetScreen.frame
        let vFrame = targetScreen.visibleFrame

        if #available(macOS 12.0, *),
           let left = targetScreen.auxiliaryTopLeftArea,
           let right = targetScreen.auxiliaryTopRightArea,
           left.width > 0, right.width > 0 {
            let notchX = left.maxX
            let notchW = right.minX - left.maxX
            let notchH = left.height
            let notchY = sFrame.maxY - notchH
            let notchRect = NSRect(x: notchX, y: notchY, width: notchW, height: notchH)
            return NotchGeometry(
                hasNotch: true,
                rect: notchRect,
                notchWidth: notchW,
                notchHeight: notchH,
                screenFrame: sFrame,
                visibleFrame: vFrame
            )
        }

        // Fallback for displays without a hardware notch (external monitors, iMac, older MacBooks)
        let fallbackWidth: CGFloat = HUDTokens.fallbackCapsuleWidth
        let fallbackHeight: CGFloat = HUDCapsuleView.notchRestingHeight
        let fallbackX = vFrame.midX - (fallbackWidth / 2.0)
        let fallbackY = vFrame.maxY - fallbackHeight
        return NotchGeometry(
            hasNotch: false,
            rect: NSRect(x: fallbackX, y: fallbackY, width: fallbackWidth, height: fallbackHeight),
            notchWidth: fallbackWidth,
            notchHeight: fallbackHeight,
            screenFrame: sFrame,
            visibleFrame: vFrame
        )
    }
}

// MARK: - HUD State Definition

public enum HUDState: String, CaseIterable {
    case listening = "listening"
    case thinking = "thinking"
    case speaking = "speaking"

    public var labelText: String {
        switch self {
        case .listening:
            return "Listening..."
        case .thinking:
            return "Donna thinking..."
        case .speaking:
            return "Speaking..."
        }
    }

    public var accentColor: NSColor {
        switch self {
        case .listening:
            // Emerald True (#10b981)
            return NSColor(srgbRed: 0x10 / 255.0, green: 0xb9 / 255.0, blue: 0x81 / 255.0, alpha: 1.0)
        case .thinking:
            // SpacePilot Gold (#c9a227)
            return NSColor(srgbRed: 0xc9 / 255.0, green: 0xa2 / 255.0, blue: 0x27 / 255.0, alpha: 1.0)
        case .speaking:
            // Liquid Silver (#cfd4dc)
            return NSColor(srgbRed: 0xcf / 255.0, green: 0xd4 / 255.0, blue: 0xdc / 255.0, alpha: 1.0)
        }
    }
}

// MARK: - Kinetic Indicator View

public class HUDIndicatorView: NSView {
    private var activeLayers: [CALayer] = []
    private var waveformBars: [CALayer] = []
    private var smoothedRMS: Float = 0.0
    private var smoothedPeak: Float = 0.0
    private var decayTimer: Timer?
    private var isAcousticListening: Bool = false

    public override init(frame frameRect: NSRect) {
        super.init(frame: frameRect)
        self.wantsLayer = true
        self.layer?.masksToBounds = false
    }

    public required init?(coder: NSCoder) {
        super.init(coder: coder)
        self.wantsLayer = true
        self.layer?.masksToBounds = false
    }

    deinit {
        decayTimer?.invalidate()
    }

    public override func setFrameSize(_ newSize: NSSize) {
        super.setFrameSize(newSize)
        if isAcousticListening {
            applyBarHeights()
        }
    }

    public func configure(for state: HUDState) {
        guard let layer = self.layer else { return }

        decayTimer?.invalidate()
        decayTimer = nil
        smoothedRMS = 0.0
        smoothedPeak = 0.0
        isAcousticListening = false
        waveformBars.removeAll()

        // Remove existing sublayers and active animations
        activeLayers.forEach { $0.removeAllAnimations(); $0.removeFromSuperlayer() }
        activeLayers.removeAll()

        switch state {
        case .listening:
            setupListeningWaveform(parentLayer: layer, color: state.accentColor)
        case .thinking:
            setupThinkingSpinner(parentLayer: layer, color: state.accentColor)
        case .speaking:
            setupSpeakingAudioBars(parentLayer: layer, color: state.accentColor)
        }
    }

    // [LISTENING] Emerald True acoustic waveform bars (Acoustic Truth: zero fake looping animations)
    private func setupListeningWaveform(parentLayer: CALayer, color: NSColor) {
        isAcousticListening = true
        waveformBars.removeAll()

        let barCount = 4
        let barWidth: CGFloat = 2.0
        let spacing: CGFloat = 2.0
        let minHeight: CGFloat = 3.5

        let totalW = CGFloat(barCount) * barWidth + CGFloat(barCount - 1) * spacing
        let startX: CGFloat = (bounds.width - totalW) / 2.0
        let centerY = bounds.height / 2.0

        for index in 0..<barCount {
            let barLayer = CALayer()
            let x = startX + CGFloat(index) * (barWidth + spacing)
            barLayer.frame = CGRect(x: x, y: centerY - minHeight / 2.0, width: barWidth, height: minHeight)
            barLayer.cornerRadius = barWidth / 2.0
            barLayer.backgroundColor = color.cgColor

            barLayer.shadowColor = color.cgColor
            barLayer.shadowRadius = 3.0
            barLayer.shadowOpacity = 0.55
            barLayer.shadowOffset = .zero

            parentLayer.addSublayer(barLayer)
            activeLayers.append(barLayer)
            waveformBars.append(barLayer)
        }
    }

    /// Update live acoustic energy levels (RMS and Peak amplitude, normalized 0.0 ... 1.0)
    public func updateAudioLevel(rms: Float, peak: Float) {
        if !Thread.isMainThread {
            DispatchQueue.main.async { [weak self] in
                self?.updateAudioLevel(rms: rms, peak: peak)
            }
            return
        }

        guard isAcousticListening, !waveformBars.isEmpty else { return }

        // Normalize inputs (safely handles raw 16-bit PCM scale or 0.0 ... 1.0)
        let normRMS: Float = rms > 1.0 ? min(1.0, max(0.0, rms / 8000.0)) : min(1.0, max(0.0, rms))
        let normPeak: Float = peak > 1.0 ? min(1.0, max(0.0, peak / 32768.0)) : min(1.0, max(0.0, peak))

        // Vocal cord acoustic filtering:
        // Fast attack (~15ms) for crisp vocal onset, smooth springy decay to eliminate digital jitter
        if normRMS > smoothedRMS {
            smoothedRMS = smoothedRMS * 0.22 + normRMS * 0.78
        } else {
            smoothedRMS = smoothedRMS * 0.76 + normRMS * 0.24
        }

        if normPeak > smoothedPeak {
            smoothedPeak = normPeak
        } else {
            smoothedPeak = smoothedPeak * 0.80
        }

        applyBarHeights()
        startDecayTimerIfNeeded()
    }

    private func applyBarHeights() {
        guard isAcousticListening, !waveformBars.isEmpty else { return }

        let barCount = waveformBars.count
        let barWidth: CGFloat = 2.0
        let spacing: CGFloat = 2.0
        let totalW = CGFloat(barCount) * barWidth + CGFloat(barCount - 1) * spacing
        let startX = (bounds.width - totalW) / 2.0
        let centerY = bounds.height / 2.0
        let minHeight: CGFloat = 3.5
        let maxHeight: CGFloat = max(minHeight, bounds.height > 4 ? bounds.height - 3.0 : 15.0)

        // Vocal formant frequency weights across 4 bars (low resonance, core vocal 1 & 2, high sibilance)
        let weights: [(rms: Float, peak: Float)] = [
            (rms: 0.65, peak: 0.25),
            (rms: 1.00, peak: 0.35),
            (rms: 0.90, peak: 0.45),
            (rms: 0.55, peak: 0.35)
        ]

        CATransaction.begin()
        CATransaction.setAnimationDuration(0.04)
        CATransaction.setAnimationTimingFunction(CAMediaTimingFunction(name: .easeOut))

        for (index, bar) in waveformBars.enumerated() {
            let w = index < weights.count ? weights[index] : (rms: 0.8, peak: 0.3)
            let energy = min(1.0, max(0.0, smoothedRMS * w.rms + smoothedPeak * w.peak))
            let barH = minHeight + CGFloat(energy) * (maxHeight - minHeight)
            let x = startX + CGFloat(index) * (barWidth + spacing)
            let y = centerY - (barH / 2.0)
            bar.frame = CGRect(x: x, y: y, width: barWidth, height: barH)
        }

        CATransaction.commit()
    }

    private func startDecayTimerIfNeeded() {
        guard decayTimer == nil else { return }
        decayTimer = Timer.scheduledTimer(withTimeInterval: 0.033, repeats: true) { [weak self] timer in
            guard let self = self else {
                timer.invalidate()
                return
            }
            if !self.isAcousticListening || self.waveformBars.isEmpty {
                timer.invalidate()
                self.decayTimer = nil
                return
            }

            if self.smoothedRMS > 0.005 || self.smoothedPeak > 0.005 {
                self.smoothedRMS *= 0.78
                self.smoothedPeak *= 0.80
                self.applyBarHeights()
            } else {
                self.smoothedRMS = 0.0
                self.smoothedPeak = 0.0
                self.applyBarHeights()
                timer.invalidate()
                self.decayTimer = nil
            }
        }
    }

    // [THINKING] SpacePilot Gold spinning orbit indicator
    private func setupThinkingSpinner(parentLayer: CALayer, color: NSColor) {
        let spinnerLayer = CAShapeLayer()
        let radius: CGFloat = 6.5
        let center = CGPoint(x: bounds.width / 2.0, y: bounds.height / 2.0)

        let path = CGMutablePath()
        path.addArc(
            center: center,
            radius: radius,
            startAngle: 0,
            endAngle: CGFloat(Double.pi * 1.5), // 270 degree open arc
            clockwise: false
        )

        spinnerLayer.bounds = bounds
        spinnerLayer.position = center
        spinnerLayer.path = path
        spinnerLayer.fillColor = nil
        spinnerLayer.strokeColor = color.cgColor
        spinnerLayer.lineWidth = 2.0
        spinnerLayer.lineCap = .round

        spinnerLayer.shadowColor = color.cgColor
        spinnerLayer.shadowRadius = 3.0
        spinnerLayer.shadowOpacity = 0.6
        spinnerLayer.shadowOffset = .zero

        let rotation = CABasicAnimation(keyPath: "transform.rotation.z")
        rotation.fromValue = 0
        rotation.toValue = -Double.pi * 2.0
        rotation.duration = 0.75
        rotation.repeatCount = .infinity
        rotation.isRemovedOnCompletion = false

        spinnerLayer.add(rotation, forKey: "thinkingSpin")
        parentLayer.addSublayer(spinnerLayer)
        activeLayers.append(spinnerLayer)
    }

    // [SPEAKING] Liquid Silver kinetic audio bars
    private func setupSpeakingAudioBars(parentLayer: CALayer, color: NSColor) {
        let barWidth: CGFloat = 2.0
        let spacing: CGFloat = 2.5
        let bars: [(initial: CGFloat, target: CGFloat, duration: Double)] = [
            (initial: 4.0, target: 12.0, duration: 0.30),
            (initial: 11.0, target: 16.0, duration: 0.38),
            (initial: 6.0, target: 14.0, duration: 0.26),
            (initial: 12.0, target: 5.0, duration: 0.34)
        ]

        let totalWidth = CGFloat(bars.count) * barWidth + CGFloat(bars.count - 1) * spacing
        let startX = (bounds.width - totalWidth) / 2.0
        let centerY = bounds.height / 2.0

        for (index, cfg) in bars.enumerated() {
            let bar = CALayer()
            let x = startX + CGFloat(index) * (barWidth + spacing)
            bar.frame = CGRect(x: x, y: centerY - cfg.initial / 2.0, width: barWidth, height: cfg.initial)
            bar.cornerRadius = barWidth / 2.0
            bar.backgroundColor = color.cgColor

            bar.shadowColor = color.cgColor
            bar.shadowRadius = 2.0
            bar.shadowOpacity = 0.4
            bar.shadowOffset = .zero

            let anim = CABasicAnimation(keyPath: "bounds.size.height")
            anim.fromValue = cfg.initial
            anim.toValue = cfg.target
            anim.duration = cfg.duration
            anim.autoreverses = true
            anim.repeatCount = .infinity
            anim.timingFunction = CAMediaTimingFunction(name: .easeInEaseOut)

            bar.add(anim, forKey: "kineticAudioBar")
            parentLayer.addSublayer(bar)
            activeLayers.append(bar)
        }
    }
}

// MARK: - Capsule Content View (Notch Dynamic Island)

public class HUDCapsuleView: NSView {
    /// The measured hardware notch width in points, or nil when this screen has
    /// no notch (external display, iMac, pre-2021 MacBook).
    public static func measuredNotchWidth(for screen: NSScreen? = nil) -> CGFloat? {
        let geometry = NotchManager.shared.currentNotch(for: screen)
        guard geometry.hasNotch, geometry.notchWidth > 0 else { return nil }
        return geometry.notchWidth
    }

    /// Resting capsule width: exactly the notch we measured, or the fallback pill.
    /// Never a hardcoded number — a 14-inch, a 16-inch and an external display all
    /// report different widths.
    public static var capsuleWidth: CGFloat { measuredNotchWidth() ?? HUDTokens.fallbackCapsuleWidth }
    public static var expandedWidth: CGFloat { HUDTokens.expandedWidth }
    public static let capsuleHeight: CGFloat = 44.0
    public static var capsuleRadius: CGFloat { HUDTokens.pillCornerRadius }

    // Notch specific dynamic metrics
    public static let notchRestingHeight: CGFloat = 38.0
    public static let notchListeningHeight: CGFloat = 52.0
    public static let notchExpandedHeight: CGFloat = 60.0
    public static let maxExpandedHeight: CGFloat = 110.0
    public static var earFilletRadius: CGFloat { HUDTokens.earFilletRadius }
    public static var bottomCornerRadius: CGFloat { HUDTokens.bottomCornerRadius }
    public static let hoverPeekHeight: CGFloat = 6.0

    // Flipped coordinates: (0, 0) is top-left, making top-edge anchoring clean and deterministic
    public override var isFlipped: Bool { return true }

    private let maskShapeLayer = CAShapeLayer()
    private let borderShapeLayer = CAShapeLayer()
    private let visualEffectView = NSVisualEffectView()
    private let obsidianBackgroundLayer = CALayer()

    public let indicatorView = HUDIndicatorView()
    public let personaBadge = NSTextField()
    public let labelField = NSTextField()
    public let goldDotLayer = CALayer()
    private var trackingArea: NSTrackingArea?

    private var currentWidth: CGFloat = HUDCapsuleView.capsuleWidth
    private var currentHeight: CGFloat = HUDCapsuleView.notchListeningHeight
    private var hasNotch: Bool = true

    public override init(frame frameRect: NSRect) {
        let notchInfo = NotchManager.shared.currentNotch()
        let initialH = notchInfo.hasNotch ? Self.notchListeningHeight : Self.capsuleHeight
        super.init(frame: NSRect(x: 0, y: 0, width: Self.capsuleWidth, height: initialH))
        self.hasNotch = notchInfo.hasNotch
        self.currentHeight = initialH
        setupView()
    }

    public required init?(coder: NSCoder) {
        super.init(coder: coder)
        setupView()
    }

    private func setupView() {
        self.wantsLayer = true
        guard let rootLayer = self.layer else { return }

        rootLayer.masksToBounds = true

        // 1. Frosted glass backdrop (.behindWindow)
        visualEffectView.frame = bounds
        visualEffectView.autoresizingMask = [.width, .height]
        visualEffectView.material = .hudWindow
        visualEffectView.blendingMode = .behindWindow
        visualEffectView.state = .active
        visualEffectView.wantsLayer = true
        addSubview(visualEffectView)

        // 2. Obsidian Jet Black & Deep Zinc surface overlay
        obsidianBackgroundLayer.frame = bounds
        // Pitch black (#000000) base matching physical notch glass with subtle deep zinc warmth
        obsidianBackgroundLayer.backgroundColor = NSColor(
            srgbRed: 0x08 / 255.0,
            green: 0x09 / 255.0,
            blue: 0x0e / 255.0,
            alpha: 0.95
        ).cgColor
        rootLayer.insertSublayer(obsidianBackgroundLayer, above: visualEffectView.layer)

        // 3. Precision Border Outline Layer (1px subtle graphite stroke)
        borderShapeLayer.fillColor = nil
        borderShapeLayer.strokeColor = NSColor(
            srgbRed: 0x22 / 255.0,
            green: 0x26 / 255.0,
            blue: 0x36 / 255.0,
            alpha: 0.85
        ).cgColor
        borderShapeLayer.lineWidth = 1.0
        rootLayer.addSublayer(borderShapeLayer)

        // 4. Indicator View (Left aligned or shelf centered)
        indicatorView.frame = NSRect(x: 18, y: 22, width: 20, height: 20)
        addSubview(indicatorView)

        // 5. Persona Badge (SpacePilot Gold semibold "Donna" badge)
        personaBadge.isEditable = false
        personaBadge.isSelectable = false
        personaBadge.isBordered = false
        personaBadge.drawsBackground = false
        personaBadge.font = NSFont.systemFont(ofSize: 11.5, weight: .bold)
        personaBadge.textColor = NSColor(srgbRed: 0xc9 / 255.0, green: 0xa2 / 255.0, blue: 0x27 / 255.0, alpha: 1.0) // SpacePilot Gold
        personaBadge.stringValue = "Donna"
        personaBadge.isHidden = true
        addSubview(personaBadge)

        // 6. Status & Dictation Typography (Multi-line word wrapping)
        labelField.isEditable = false
        labelField.isSelectable = false
        labelField.isBordered = false
        labelField.drawsBackground = false
        labelField.font = NSFont.systemFont(ofSize: 12.5, weight: .medium)
        labelField.textColor = NSColor(srgbRed: 0xf3 / 255.0, green: 0xf4 / 255.0, blue: 0xf6 / 255.0, alpha: 1.0)
        labelField.alignment = .left
        labelField.lineBreakMode = .byWordWrapping
        labelField.cell?.wraps = true
        labelField.cell?.isScrollable = false
        labelField.cell?.truncatesLastVisibleLine = true
        labelField.maximumNumberOfLines = 4
        labelField.usesSingleLineMode = false
        labelField.stringValue = "Listening..."
        addSubview(labelField)

        // 7. SpacePilot Gold Dot Layer for Subtle Notch Peek
        goldDotLayer.bounds = CGRect(x: 0, y: 0, width: 6.0, height: 6.0)
        goldDotLayer.cornerRadius = 3.0
        let goldColor = NSColor(srgbRed: 0xc9 / 255.0, green: 0xa2 / 255.0, blue: 0x27 / 255.0, alpha: 1.0)
        goldDotLayer.backgroundColor = goldColor.cgColor
        goldDotLayer.shadowColor = goldColor.cgColor
        goldDotLayer.shadowRadius = 3.0
        goldDotLayer.shadowOpacity = 0.8
        goldDotLayer.shadowOffset = .zero
        goldDotLayer.opacity = 0.0
        rootLayer.addSublayer(goldDotLayer)

        updateShapePath(width: bounds.width, height: bounds.height)
        layoutSubviews(forWidth: bounds.width, height: bounds.height)
    }

    public override func updateTrackingAreas() {
        super.updateTrackingAreas()
        if let existing = trackingArea {
            removeTrackingArea(existing)
        }
        let options: NSTrackingArea.Options = [
            .mouseEnteredAndExited,
            .activeAlways,
            .inVisibleRect
        ]
        let newArea = NSTrackingArea(rect: bounds, options: options, owner: self, userInfo: nil)
        addTrackingArea(newArea)
        trackingArea = newArea
    }

    public override func mouseEntered(with event: NSEvent) {
        super.mouseEntered(with: event)
        HUDController.shared.handleMouseEntered()
    }

    public override func mouseExited(with event: NSEvent) {
        super.mouseExited(with: event)
        HUDController.shared.handleMouseExited()
    }

    public override func mouseDown(with event: NSEvent) {
        super.mouseDown(with: event)
        HUDController.shared.handleCapsuleClick()
    }

    /// Ear fillets appear only once the content actually spills past the notch:
    /// measured notch width plus the threshold token, never a fixed width.
    /// Public so `--self-test` can assert the decision headlessly.
    public static func earFilletRadius(forWidth width: CGFloat, notchWidth: CGFloat) -> CGFloat {
        return width > notchWidth + HUDTokens.earFilletThreshold ? HUDTokens.earFilletRadius : 0.0
    }

    /// Construct Apple-grade Dynamic Island Bezier path:
    /// - Continuous squircle bottom corners (r=20px).
    /// - Top edge flush with display bezel (y=0).
    /// - Concave ear fillets (r=10px) that sweep outward smoothly into the top bezel when expanded.
    private func createDynamicIslandPath(width: CGFloat, height: CGFloat) -> CGPath {
        let path = CGMutablePath()
        let bottomRadius: CGFloat = HUDTokens.bottomCornerRadius
        let notchInfo = NotchManager.shared.currentNotch()

        if !notchInfo.hasNotch {
            // External monitor: symmetrical floating pill
            let radius = min(Self.capsuleRadius, height / 2.0)
            path.addRoundedRect(
                in: CGRect(x: 0, y: 0, width: width, height: height),
                cornerWidth: radius,
                cornerHeight: radius
            )
            return path
        }

        let earRadius: CGFloat = Self.earFilletRadius(
            forWidth: width,
            notchWidth: notchInfo.notchWidth
        )

        if earRadius > 0 {
            // Left ear concave swoop into top bezel
            path.move(to: CGPoint(x: 0, y: 0))
            path.addQuadCurve(
                to: CGPoint(x: earRadius, y: earRadius),
                control: CGPoint(x: earRadius, y: 0)
            )
            path.addLine(to: CGPoint(x: earRadius, y: height - bottomRadius))
        } else {
            path.move(to: CGPoint(x: 0, y: 0))
            path.addLine(to: CGPoint(x: 0, y: height - bottomRadius))
        }

        // Bottom-left corner
        let leftBottomX = earRadius > 0 ? earRadius : 0.0
        path.addArc(
            tangent1End: CGPoint(x: leftBottomX, y: height),
            tangent2End: CGPoint(x: leftBottomX + bottomRadius, y: height),
            radius: bottomRadius
        )

        // Bottom horizontal shelf
        let rightBottomX = earRadius > 0 ? (width - earRadius) : width
        path.addLine(to: CGPoint(x: rightBottomX - bottomRadius, y: height))

        // Bottom-right corner
        path.addArc(
            tangent1End: CGPoint(x: rightBottomX, y: height),
            tangent2End: CGPoint(x: rightBottomX, y: height - bottomRadius),
            radius: bottomRadius
        )

        if earRadius > 0 {
            path.addLine(to: CGPoint(x: width - earRadius, y: earRadius))
            // Right ear concave swoop into top bezel
            path.addQuadCurve(
                to: CGPoint(x: width, y: 0),
                control: CGPoint(x: width - earRadius, y: 0)
            )
        } else {
            path.addLine(to: CGPoint(x: width, y: 0))
        }

        path.closeSubpath()
        return path
    }

    public func updateShapePath(width: CGFloat, height: CGFloat) {
        let cgPath = createDynamicIslandPath(width: width, height: height)

        maskShapeLayer.path = cgPath
        self.layer?.mask = maskShapeLayer

        borderShapeLayer.path = cgPath
        obsidianBackgroundLayer.frame = CGRect(x: 0, y: 0, width: width, height: height)
        visualEffectView.frame = NSRect(x: 0, y: 0, width: width, height: height)
    }

    public static func calculateTextHeight(for attrString: NSAttributedString, constrainedToWidth width: CGFloat) -> CGFloat {
        let size = CGSize(width: width, height: CGFloat.greatestFiniteMagnitude)
        let rect = attrString.boundingRect(
            with: size,
            options: [.usesLineFragmentOrigin, .usesFontLeading],
            context: nil
        )
        return ceil(rect.height)
    }

    public static func computeDynamicNotchHeight(for textHeight: CGFloat, hasNotch: Bool) -> CGFloat {
        if hasNotch {
            if textHeight <= 22.0 {
                return notchExpandedHeight // 60.0px (single line)
            } else if textHeight <= 42.0 {
                return 76.0 // 2 lines
            } else if textHeight <= 62.0 {
                return 96.0 // 3 lines
            } else {
                return maxExpandedHeight // 110.0px (4 lines clamp)
            }
        } else {
            if textHeight <= 22.0 {
                return capsuleHeight // 44.0px
            } else if textHeight <= 42.0 {
                return 64.0 // 2 lines
            } else if textHeight <= 62.0 {
                return 82.0 // 3 lines
            } else {
                return 96.0 // 4 lines
            }
        }
    }

    public func layoutSubviews(forWidth width: CGFloat, height: CGFloat) {
        self.currentWidth = width
        self.currentHeight = height
        self.frame = NSRect(x: 0, y: 0, width: width, height: height)

        updateShapePath(width: width, height: height)

        let isExpanded = width > (Self.capsuleWidth + 40.0)
        let notchInfo = NotchManager.shared.currentNotch()

        if isExpanded {
            if notchInfo.hasNotch {
                // Expanded wings layout (flanking notch core + downward shelf)
                personaBadge.isHidden = false
                // Persona badge in the open left ear wing flanking the hardware notch
                personaBadge.frame = NSRect(x: 20, y: 10, width: 64, height: 18)
                // Status indicator on shelf below physical notch
                indicatorView.frame = NSRect(x: 20, y: 41, width: 16, height: 16)
                // Multi-line word-wrapping label spanning width below notch
                let textTop: CGFloat = 38.0
                let textH = max(20.0, height - textTop - 10.0)
                labelField.frame = NSRect(x: 44, y: textTop, width: width - 64, height: textH)
            } else {
                // External monitor floating layout
                personaBadge.isHidden = false
                indicatorView.frame = NSRect(x: 16, y: 14, width: 16, height: 16)
                personaBadge.frame = NSRect(x: 38, y: 13, width: 50, height: 18)
                let textTop: CGFloat = 12.0
                let textH = max(20.0, height - textTop - 10.0)
                labelField.frame = NSRect(x: 94, y: textTop, width: width - 110, height: textH)
            }
        } else {
            // Compact shelf layout right beneath camera lens
            personaBadge.isHidden = true
            if notchInfo.hasNotch {
                indicatorView.frame = NSRect(x: 18, y: 38, width: 14, height: 14)
                labelField.frame = NSRect(x: 38, y: 36, width: width - 48, height: 16)
            } else {
                let centerY = (height - 18.0) / 2.0
                indicatorView.frame = NSRect(x: 18, y: centerY, width: 18, height: 18)
                labelField.frame = NSRect(x: 44, y: (height - 20.0) / 2.0, width: width - 56, height: 20)
            }
        }

        // Gold dot positioned at bottom center of the shelf
        goldDotLayer.position = CGPoint(x: width / 2.0, y: height - 5.0)
    }

    public func update(state: HUDState) {
        indicatorView.configure(for: state)
        labelField.stringValue = state.labelText
        labelField.textColor = NSColor(srgbRed: 0xf3 / 255.0, green: 0xf4 / 255.0, blue: 0xf6 / 255.0, alpha: 1.0)
    }

    @discardableResult
    public func setTranscribedText(_ text: String, persona: String = "Donna") -> CGFloat {
        let cleanText = text.trimmingCharacters(in: .whitespacesAndNewlines)

        let attr = NSMutableAttributedString()
        let prefixAttr: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 12.0, weight: .bold),
            .foregroundColor: NSColor(srgbRed: 0xc9 / 255.0, green: 0xa2 / 255.0, blue: 0x27 / 255.0, alpha: 1.0) // SpacePilot Gold
        ]
        let textAttr: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 12.5, weight: .medium),
            .foregroundColor: NSColor(srgbRed: 0xf3 / 255.0, green: 0xf4 / 255.0, blue: 0xf6 / 255.0, alpha: 1.0) // Zinc White
        ]

        let prefixStr = "[\(persona) heard]: "
        attr.append(NSAttributedString(string: prefixStr, attributes: prefixAttr))
        attr.append(NSAttributedString(string: "\"\(cleanText)\"", attributes: textAttr))

        labelField.attributedStringValue = attr
        labelField.toolTip = "[\(persona) heard]: \"\(cleanText)\""

        let availableWidth = Self.expandedWidth - 64.0
        let textH = Self.calculateTextHeight(for: attr, constrainedToWidth: availableWidth)
        let notchInfo = NotchManager.shared.currentNotch()
        return Self.computeDynamicNotchHeight(for: textH, hasNotch: notchInfo.hasNotch)
    }

    @discardableResult
    public func setBreadcrumb(badge: String, detail: String, accentColor: NSColor) -> CGFloat {
        let cleanDetail = detail.trimmingCharacters(in: .whitespacesAndNewlines)

        let attr = NSMutableAttributedString()
        let prefixAttr: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 12.0, weight: .bold),
            .foregroundColor: accentColor
        ]
        let textAttr: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 12.5, weight: .medium),
            .foregroundColor: NSColor(srgbRed: 0xf3 / 255.0, green: 0xf4 / 255.0, blue: 0xf6 / 255.0, alpha: 1.0) // Zinc White
        ]

        let prefixStr = "[\(badge)]: "
        attr.append(NSAttributedString(string: prefixStr, attributes: prefixAttr))
        attr.append(NSAttributedString(string: cleanDetail, attributes: textAttr))

        labelField.attributedStringValue = attr
        labelField.toolTip = "[\(badge)]: \(cleanDetail)"

        let availableWidth = Self.expandedWidth - 64.0
        let textH = Self.calculateTextHeight(for: attr, constrainedToWidth: availableWidth)
        let notchInfo = NotchManager.shared.currentNotch()
        return Self.computeDynamicNotchHeight(for: textH, hasNotch: notchInfo.hasNotch)
    }

    public func reset() {
        let notchInfo = NotchManager.shared.currentNotch()
        let defaultH = notchInfo.hasNotch ? Self.notchListeningHeight : Self.capsuleHeight
        layer?.removeAnimation(forKey: "hudSpringFade")
        layer?.opacity = 1.0
        layoutSubviews(forWidth: Self.capsuleWidth, height: defaultH)
        labelField.stringValue = "Listening..."
        labelField.textColor = NSColor(srgbRed: 0xf3 / 255.0, green: 0xf4 / 255.0, blue: 0xf6 / 255.0, alpha: 1.0)
        goldDotLayer.opacity = 0.0
        indicatorView.isHidden = false
    }

    public func updateAudioLevel(rms: Float, peak: Float) {
        indicatorView.updateAudioLevel(rms: rms, peak: peak)
    }
}

// MARK: - HUDPanel (Native Non-Activating NSPanel)

open class HUDPanel: NSPanel {
    public let capsuleView = HUDCapsuleView()

    public init() {
        let contentRect = NSRect(
            x: 0,
            y: 0,
            width: HUDCapsuleView.capsuleWidth,
            height: HUDCapsuleView.notchListeningHeight
        )

        super.init(
            contentRect: contentRect,
            styleMask: [.nonactivatingPanel, .borderless],
            backing: .buffered,
            defer: false
        )

        // Window specifications:
        self.level = .floating
        self.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
        self.ignoresMouseEvents = true
        self.isOpaque = false
        self.backgroundColor = .clear
        self.hasShadow = true
        self.isMovableByWindowBackground = false
        self.isReleasedWhenClosed = false

        self.contentView = capsuleView
    }

    // Crucial: Never steal keyboard focus or become key/main window
    open override var canBecomeKey: Bool { return false }
    open override var canBecomeMain: Bool { return false }
}

// MARK: - HUDController Singleton

/// Single-state lifecycle for the HUD panel. Replaces the old boolean `isVisible`
/// plus ad-hoc animation bookkeeping so show()/dismiss() can never race each other:
/// each transition bumps `generation`, and any completion handler scheduled by a
/// prior transition checks its captured generation before mutating state — a
/// stale dismiss cleanup from before a newer show() is a no-op.
public enum HUDLifecycle {
    case hidden
    case presenting
    case visible
    case dismissing
}

public class HUDController {
    public static let shared = HUDController()

    public let panel = HUDPanel()
    public private(set) var currentState: HUDState?
    public private(set) var currentWidth: CGFloat = HUDCapsuleView.capsuleWidth
    public private(set) var currentHeight: CGFloat = HUDCapsuleView.notchListeningHeight
    public private(set) var transcribedText: String?
    public private(set) var lifecycle: HUDLifecycle = .hidden
    public var isVisible: Bool { lifecycle == .presenting || lifecycle == .visible || lifecycle == .dismissing }
    public private(set) var isHoverPeekActive: Bool = false

    /// Bumped on every show()/dismiss() call. A completion handler captures the
    /// generation at schedule time and only applies its cleanup if it is still
    /// current — this is what makes a stale dismiss never clobber a newer show.
    private var generation: Int = 0

    // Sensory & Execution Callbacks
    public var onBargeKill: (() -> Void)?
    public var onErrorAudio: (() -> Void)?
    public var onTriggerTurn: (() -> Void)?

    private var localKeyMonitor: Any?
    private var globalMouseMonitor: Any?

    /// The in-flight geometry spring, if any. Cancelled by any newer transition
    /// and by the barge hard cut.
    private var frameSpring: HUDSpringDriver?

    /// PET_TALK_HEADLESS=1 runs every state transition, spring step and geometry
    /// computation as usual but never puts a panel on screen. The QA suites set
    /// it, so a test can never pop the capsule onto the screen someone is working
    /// on (Saurabh, 2026-09-12).
    public static var isHeadless: Bool {
        let raw = (ProcessInfo.processInfo.environment["PET_TALK_HEADLESS"] ?? "").lowercased()
        return raw == "1" || raw == "true" || raw == "yes"
    }

    /// Every path that would show the panel goes through here.
    private func orderFrontUnlessHeadless() {
        guard !HUDController.isHeadless else { return }
        panel.orderFrontRegardless()
    }

    private init() {}

    private enum SpringFade {
        case none
        case fadeIn
        case fadeOut
    }

    /// Drive the panel from one pose to another under the declared damped spring.
    /// Frame geometry is integrated by HUDSpringDriver (a window frame is not
    /// animatable by Core Animation); the capsule's opacity rides a real
    /// CASpringAnimation. Both read the same three tokens, so they settle together.
    private func springGeometry(
        fromWidth: CGFloat,
        fromHeight: CGFloat,
        toWidth: CGFloat,
        toHeight: CGFloat,
        fade: SpringFade = .none,
        completion: (() -> Void)? = nil
    ) {
        frameSpring?.cancel()

        if fade != .none, let layer = panel.capsuleView.layer {
            let from: Float = (fade == .fadeIn) ? 0.0 : 1.0
            let to: Float = (fade == .fadeIn) ? 1.0 : 0.0
            layer.removeAnimation(forKey: "hudSpringFade")
            layer.add(HUDSpring.animation(keyPath: "opacity", from: from, to: to), forKey: "hudSpringFade")
            layer.opacity = to
        }

        let driver = HUDSpringDriver(onStep: { [weak self] progress in
            guard let self = self else { return }
            let p = CGFloat(progress)
            let w = max(1.0, fromWidth + (toWidth - fromWidth) * p)
            let h = max(1.0, fromHeight + (toHeight - fromHeight) * p)
            CATransaction.begin()
            CATransaction.setDisableActions(true)
            self.panel.setFrame(self.computeFrame(width: w, height: h), display: false)
            self.panel.capsuleView.layoutSubviews(forWidth: w, height: h)
            CATransaction.commit()
        }, onDone: { [weak self] in
            guard let self = self else { return }
            self.frameSpring = nil
            self.panel.invalidateShadow()
            completion?()
        })
        frameSpring = driver
        driver.start()
    }

    /// Register local Escape monitor and global notch hover tracking
    public func setupEventMonitors() {
        ensureMainThread {
            if self.localKeyMonitor == nil {
                self.localKeyMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { [weak self] event in
                    guard let self = self else { return event }
                    // Escape key (keycode 53): instant <= 50ms dismiss and barge-kill
                    if event.keyCode == 53 && (self.isVisible || self.isHoverPeekActive) {
                        self.dismissWithBargeKill()
                        return nil
                    }
                    return event
                }
            }

            if self.globalMouseMonitor == nil {
                self.globalMouseMonitor = NSEvent.addGlobalMonitorForEvents(matching: .mouseMoved) { [weak self] _ in
                    guard let self = self else { return }
                    let mouseLoc = NSEvent.mouseLocation
                    let notchInfo = NotchManager.shared.currentNotch()
                    guard notchInfo.hasNotch else { return }

                    let notchH = notchInfo.notchHeight
                    let notchW = HUDCapsuleView.capsuleWidth
                    let notchX = notchInfo.screenFrame.midX - (notchW / 2.0)
                    let notchY = notchInfo.screenFrame.maxY - notchH - HUDCapsuleView.hoverPeekHeight
                    let notchZone = NSRect(
                        x: notchX,
                        y: notchY,
                        width: notchW,
                        height: notchH + HUDCapsuleView.hoverPeekHeight + 4.0
                    )

                    if notchZone.contains(mouseLoc) {
                        if !self.isVisible && !self.isHoverPeekActive {
                            self.showHoverPeek()
                        }
                    } else {
                        if self.isHoverPeekActive {
                            self.hideHoverPeek()
                        }
                    }
                }
            }
        }
    }

    /// Subtle notch hover peek (6px downward expansion revealing SpacePilot Gold dot)
    public func showHoverPeek() {
        ensureMainThread {
            guard !self.isVisible, !self.isHoverPeekActive else { return }
            let notchInfo = NotchManager.shared.currentNotch()
            guard notchInfo.hasNotch else { return }

            self.isHoverPeekActive = true
            let peekH = notchInfo.notchHeight + HUDCapsuleView.hoverPeekHeight
            let frame = self.computeFrame(width: HUDCapsuleView.capsuleWidth, height: peekH)

            self.panel.ignoresMouseEvents = false
            self.panel.setFrame(frame, display: true)
            self.panel.alphaValue = 1.0
            self.panel.capsuleView.goldDotLayer.opacity = 1.0
            self.panel.capsuleView.indicatorView.isHidden = true
            self.panel.capsuleView.labelField.stringValue = ""
            self.orderFrontUnlessHeadless()
        }
    }

    /// Snap hover peek back into the physical notch
    public func hideHoverPeek() {
        ensureMainThread {
            guard self.isHoverPeekActive else { return }
            self.isHoverPeekActive = false
            self.panel.ignoresMouseEvents = true
            self.panel.capsuleView.goldDotLayer.opacity = 0.0
            self.panel.capsuleView.indicatorView.isHidden = false
            self.panel.orderOut(nil)
        }
    }

    public func handleMouseEntered() {
        showHoverPeek()
    }

    public func handleMouseExited() {
        hideHoverPeek()
    }

    public func handleCapsuleClick() {
        ensureMainThread {
            if self.isHoverPeekActive {
                self.hideHoverPeek()
                if let trigger = self.onTriggerTurn {
                    trigger()
                } else {
                    self.show(state: .listening)
                }
            }
        }
    }

    /// Instant Escape dismiss: terminates active speech/processes in <= 50ms
    public func dismissWithBargeKill() {
        ensureMainThread {
            self.onBargeKill?()
            if self.isHoverPeekActive {
                self.hideHoverPeek()
            }
            if self.isVisible {
                self.dismiss(hardCut: true)
            }
        }
    }

    /// 3-cycle horizontal micro-shake feedback (±3px over 120ms) + Basso chime
    public func triggerErrorShake(completion: (() -> Void)? = nil) {
        ensureMainThread {
            guard self.isVisible else {
                completion?()
                return
            }

            if let audio = self.onErrorAudio {
                audio()
            } else if !EarconEngine.isSilentModeEnv && !HUDController.isHeadless {
                NSSound(named: "Basso")?.play()
            }

            guard !NSWorkspace.shared.accessibilityDisplayShouldReduceMotion else {
                completion?()
                return
            }

            // N cycles of +/- amplitude, both read from tokens, decaying to rest.
            let amplitude = HUDMotionTokens.errorShakeAmplitude
            let cycles = max(1, HUDMotionTokens.errorShakeCycles)
            var values: [Double] = [0.0]
            for cycle in 0..<cycles {
                let decay = 1.0 - (Double(cycle) / Double(cycles)) * 0.35
                values.append(-amplitude * decay)
                values.append(amplitude * decay)
            }
            values.append(0.0)

            let shake = CAKeyframeAnimation(keyPath: "transform.translation.x")
            shake.duration = HUDMotionTokens.errorShakeDuration
            shake.values = values
            shake.timingFunction = CAMediaTimingFunction(name: .easeInEaseOut)
            shake.isRemovedOnCompletion = true
            self.panel.capsuleView.layer?.add(shake, forKey: "errorShake")

            DispatchQueue.main.asyncAfter(deadline: .now() + HUDMotionTokens.errorShakeDuration) {
                completion?()
            }
        }
    }

    /// Alias for triggerErrorShake
    public func shakeError(completion: (() -> Void)? = nil) {
        triggerErrorShake(completion: completion)
    }

    /// Real-time microphone acoustic energy levels (RMS / peak, normalized 0.0 ... 1.0)
    public func updateAudioLevel(rms: Float, peak: Float) {
        ensureMainThread {
            guard self.isVisible, self.currentState == .listening else { return }
            self.panel.capsuleView.updateAudioLevel(rms: rms, peak: peak)
        }
    }

    /// Present the Dynamic Island with Apple-grade "Drip" spring entrance animation.
    ///
    /// Idempotent: if the HUD is already visible (or mid-dismiss), this cancels any
    /// in-flight dismiss animation, snaps alphaValue back to 1 immediately, and
    /// bumps `generation` so that dismiss's own completion handler (scheduled
    /// before this call) sees a stale generation and never fires its cleanup —
    /// no stale hide can land on top of this newer show.
    public func show(state: HUDState = .listening) {
        ensureMainThread {
            self.generation += 1
            let myGen = self.generation

            if self.isHoverPeekActive {
                self.hideHoverPeek()
            }

            let notchInfo = NotchManager.shared.currentNotch()
            let targetH = notchInfo.hasNotch ? HUDCapsuleView.notchListeningHeight : HUDCapsuleView.capsuleHeight
            let targetW = HUDCapsuleView.capsuleWidth

            self.currentState = state
            self.transcribedText = nil
            self.currentWidth = targetW
            self.currentHeight = targetH

            self.panel.capsuleView.reset()
            self.panel.capsuleView.update(state: state)

            let finalFrame = self.computeFrame(width: targetW, height: targetH)

            let wasHidden = (self.lifecycle == .hidden)

            if wasHidden {
                self.lifecycle = .presenting

                if NSWorkspace.shared.accessibilityDisplayShouldReduceMotion {
                    // Reduce Motion: zero spatial travel, time preserved (80ms crossfade).
                    self.panel.setFrame(finalFrame, display: false)
                    self.panel.capsuleView.layer?.opacity = 1.0
                    self.panel.alphaValue = 0.0
                    self.orderFrontUnlessHeadless()

                    NSAnimationContext.runAnimationGroup({ context in
                        context.duration = HUDMotionTokens.reduceMotionDuration
                        context.timingFunction = CAMediaTimingFunction(name: .easeOut)
                        self.panel.animator().alphaValue = 1.0
                        self.panel.capsuleView.layoutSubviews(forWidth: targetW, height: targetH)
                    }, completionHandler: {
                        guard myGen == self.generation else { return }
                        self.lifecycle = .visible
                    })
                } else {
                    // "The Drip": the notch unfolds downward under the real spring.
                    let startH = notchInfo.hasNotch ? notchInfo.notchHeight : targetH
                    self.panel.setFrame(self.computeFrame(width: targetW, height: startH), display: false)
                    self.panel.capsuleView.layoutSubviews(forWidth: targetW, height: startH)
                    self.panel.alphaValue = 1.0
                    self.orderFrontUnlessHeadless()

                    self.springGeometry(
                        fromWidth: targetW, fromHeight: startH,
                        toWidth: targetW, toHeight: targetH,
                        fade: .fadeIn
                    ) {
                        guard myGen == self.generation else { return }
                        self.lifecycle = .visible
                    }
                }
                self.panel.invalidateShadow()
            } else {
                // Already presenting/visible/dismissing: idempotent re-show. Cancel any
                // in-flight dismiss fade by snapping alpha back to 1 directly (not via
                // .animator(), which would just queue behind the running animation).
                self.frameSpring?.cancel()
                self.frameSpring = nil
                self.lifecycle = .visible
                self.panel.capsuleView.layer?.removeAnimation(forKey: "hudSpringFade")
                self.panel.capsuleView.layer?.opacity = 1.0
                self.panel.alphaValue = 1.0
                self.orderFrontUnlessHeadless()
                self.panel.setFrame(finalFrame, display: true)
                self.panel.capsuleView.layoutSubviews(forWidth: targetW, height: targetH)
                self.panel.invalidateShadow()
            }
        }
    }

    /// Expand Dynamic Island outward for dictation with dynamic multi-line height expansion (52px -> 76px -> 96px -> 110px).
    public func showTranscribedText(_ text: String, persona: String = "Donna") {
        ensureMainThread {
            self.transcribedText = text
            let targetH = self.panel.capsuleView.setTranscribedText(text, persona: persona)
            let targetW = HUDCapsuleView.expandedWidth

            self.resizeIsland(toWidth: targetW, height: targetH, animated: true)

            if !self.isVisible {
                self.show(state: .thinking)
                _ = self.panel.capsuleView.setTranscribedText(text, persona: persona)
                self.resizeIsland(toWidth: targetW, height: targetH, animated: false)
            }
        }
    }

    /// Render a high-level Semantic Action Breadcrumb (e.g. [Thinking], [Running], [Editing], [Searching], [Speaking]).
    public func showBreadcrumb(
        badge: String,
        detail: String,
        state: HUDState = .thinking,
        accentColor: NSColor? = nil
    ) {
        ensureMainThread {
            self.currentState = state
            self.panel.capsuleView.indicatorView.configure(for: state)
            let color = accentColor ?? state.accentColor
            let targetH = self.panel.capsuleView.setBreadcrumb(badge: badge, detail: detail, accentColor: color)
            let targetW = HUDCapsuleView.expandedWidth

            self.resizeIsland(toWidth: targetW, height: targetH, animated: true)

            if !self.isVisible {
                self.show(state: state)
                _ = self.panel.capsuleView.setBreadcrumb(badge: badge, detail: detail, accentColor: color)
                self.resizeIsland(toWidth: targetW, height: targetH, animated: false)
            }
        }
    }

    /// Update HUD state dynamically (e.g. listening -> thinking -> speaking).
    public func update(state: HUDState) {
        ensureMainThread {
            self.currentState = state
            let notchInfo = NotchManager.shared.currentNotch()

            if let text = self.transcribedText, !text.isEmpty {
                self.panel.capsuleView.indicatorView.configure(for: state)
                let targetH = self.panel.capsuleView.setTranscribedText(text, persona: "Donna")
                self.resizeIsland(toWidth: HUDCapsuleView.expandedWidth, height: targetH, animated: false)
            } else {
                self.panel.capsuleView.update(state: state)
                let targetH = notchInfo.hasNotch ? HUDCapsuleView.notchListeningHeight : HUDCapsuleView.capsuleHeight
                self.resizeIsland(toWidth: HUDCapsuleView.capsuleWidth, height: targetH, animated: true)
            }
            if !self.isVisible {
                self.show(state: state)
            }
        }
    }

    /// Fluidly morph island width and height with Apple-grade spring physics.
    public func resizeIsland(toWidth newWidth: CGFloat, height newHeight: CGFloat, animated: Bool = true) {
        guard self.currentWidth != newWidth || self.currentHeight != newHeight else { return }
        self.currentWidth = newWidth
        self.currentHeight = newHeight

        let newFrame = computeFrame(width: newWidth, height: newHeight)

        if animated {
            if NSWorkspace.shared.accessibilityDisplayShouldReduceMotion {
                // Zero travel: snap to the new pose, no intermediate geometry.
                self.frameSpring?.cancel()
                self.frameSpring = nil
                self.panel.setFrame(newFrame, display: true)
                self.panel.capsuleView.layoutSubviews(forWidth: newWidth, height: newHeight)
            } else {
                // "The Blossom": width and height morph under the same spring.
                self.springGeometry(
                    fromWidth: self.panel.frame.width, fromHeight: self.panel.frame.height,
                    toWidth: newWidth, toHeight: newHeight
                )
            }
        } else {
            self.frameSpring?.cancel()
            self.frameSpring = nil
            self.panel.setFrame(newFrame, display: true)
            self.panel.capsuleView.layoutSubviews(forWidth: newWidth, height: newHeight)
        }
        self.panel.invalidateShadow()
    }

    /// Dismiss the HUD with a snappy suction retraction back into the physical notch.
    ///
    /// Captures the current `generation` before scheduling any animation. If a
    /// newer show() runs before this dismiss's animation completes, show() bumps
    /// `generation` — so this dismiss's `cleanup` sees a stale generation and
    /// becomes a no-op instead of hiding the panel out from under the newer show.
    /// `hardCut: true` is the barge/Escape path: an instant stop with zero
    /// animation. Anything else retracts under the spring.
    public func dismiss(hardCut: Bool = false, completion: (() -> Void)? = nil) {
        ensureMainThread {
            guard self.isVisible else {
                completion?()
                return
            }

            self.generation += 1
            let myGen = self.generation
            self.lifecycle = .dismissing

            let cleanup: () -> Void = {
                guard myGen == self.generation else {
                    // Superseded by a newer show()/dismiss() — do not touch state
                    // or hide a panel that a later call already took ownership of.
                    completion?()
                    return
                }
                self.panel.orderOut(nil)
                self.lifecycle = .hidden
                self.currentState = nil
                self.transcribedText = nil
                let notchInfo = NotchManager.shared.currentNotch()
                self.currentWidth = HUDCapsuleView.capsuleWidth
                self.currentHeight = notchInfo.hasNotch ? HUDCapsuleView.notchListeningHeight : HUDCapsuleView.capsuleHeight
                self.panel.capsuleView.reset()
                completion?()
            }

            if hardCut {
                // HARD CUT: a barge is a stop, not a transition. No spring, no
                // fade, no animation of any kind — the panel is gone on this turn
                // of the run loop, inside the 50ms budget by construction.
                self.frameSpring?.cancel()
                self.frameSpring = nil
                self.panel.capsuleView.layer?.removeAllAnimations()
                self.panel.capsuleView.layer?.opacity = 1.0
                self.panel.alphaValue = 1.0
                cleanup()
                return
            }

            if NSWorkspace.shared.accessibilityDisplayShouldReduceMotion {
                // Zero travel, time kept: an 80ms crossfade in place.
                NSAnimationContext.runAnimationGroup({ context in
                    context.duration = HUDMotionTokens.reduceMotionDuration
                    self.panel.animator().alphaValue = 0.0
                }, completionHandler: {
                    cleanup()
                })
                return
            }

            let notchInfo = NotchManager.shared.currentNotch()
            // "Suction": springs back up into the physical notch as it fades.
            let retractH = notchInfo.hasNotch ? notchInfo.notchHeight : self.currentHeight
            self.springGeometry(
                fromWidth: self.panel.frame.width, fromHeight: self.panel.frame.height,
                toWidth: HUDCapsuleView.capsuleWidth, toHeight: retractH,
                fade: .fadeOut
            ) {
                cleanup()
            }
        }
    }

    /// Compute frame based on active screen notch geometry:
    /// - If hardware notch exists: anchors flush to screen.frame.maxY, centered on the notch.
    /// - If no notch: centers horizontally on visibleFrame and floats 12px below menu bar.
    public func computeFrame(width: CGFloat, height: CGFloat) -> NSRect {
        let screen = NSScreen.main ?? (NSScreen.screens.first ?? NSScreen())
        let notchInfo = NotchManager.shared.currentNotch(for: screen)

        if notchInfo.hasNotch {
            let x = notchInfo.rect.midX - (width / 2.0)
            let y = notchInfo.screenFrame.maxY - height
            return NSRect(x: x, y: y, width: width, height: height)
        } else {
            let x = notchInfo.visibleFrame.midX - (width / 2.0)
            let y = notchInfo.visibleFrame.maxY - height - 12.0
            return NSRect(x: x, y: y, width: width, height: height)
        }
    }

    private func ensureMainThread(_ block: @escaping () -> Void) {
        if Thread.isMainThread {
            block()
        } else {
            DispatchQueue.main.async(execute: block)
        }
    }

    /// Name of the current lifecycle node, for `--dump-state`.
    public var lifecycleName: String {
        switch lifecycle {
        case .hidden: return "hidden"
        case .presenting: return "presenting"
        case .visible: return "visible"
        case .dismissing: return "dismissing"
        }
    }

    /// Machine-readable snapshot for `pet-talk-hotkey --dump-state`: the state
    /// machine, the measured capsule geometry, and the spring constants actually
    /// in force (after any config.yaml override). No window is shown.
    public func getStateDump() -> [String: Any] {
        let notchInfo = NotchManager.shared.currentNotch()
        let measured = HUDCapsuleView.measuredNotchWidth()

        return [
            "state": [
                "lifecycle": lifecycleName,
                "hudState": currentState?.rawValue ?? "none",
                "hoverPeek": isHoverPeekActive,
                "reduceMotion": NSWorkspace.shared.accessibilityDisplayShouldReduceMotion,
                "transcribedText": transcribedText ?? "",
                "states": HUDState.allCases.map { $0.rawValue }
            ] as [String: Any],
            "geometry": [
                "hasNotch": notchInfo.hasNotch,
                "measuredNotchWidth": measured ?? 0.0,
                "measuredNotchHeight": notchInfo.notchHeight,
                "capsuleWidth": HUDCapsuleView.capsuleWidth,
                "currentWidth": currentWidth,
                "currentHeight": currentHeight,
                "fallbackCapsuleWidth": HUDTokens.fallbackCapsuleWidth,
                "expandedWidth": HUDCapsuleView.expandedWidth,
                "earFilletThreshold": HUDTokens.earFilletThreshold,
                "earFilletRadius": HUDCapsuleView.earFilletRadius,
                "bottomCornerRadius": HUDCapsuleView.bottomCornerRadius,
                "pillCornerRadius": HUDCapsuleView.capsuleRadius,
                "restingHeight": HUDCapsuleView.notchRestingHeight,
                "listeningHeight": HUDCapsuleView.notchListeningHeight,
                "expandedHeight": HUDCapsuleView.notchExpandedHeight,
                "maxExpandedHeight": HUDCapsuleView.maxExpandedHeight
            ] as [String: Any],
            "spring": [
                "stiffness": HUDTokens.springStiffness,
                "damping": HUDTokens.springDamping,
                "mass": HUDTokens.springMass,
                "initialVelocity": 0.0,
                "settlingDurationMs": HUDSpring.settlingDuration * 1000.0,
                "driverHz": 120.0
            ] as [String: Any],
            "motion": [
                "dripDurationMs": HUDMotionTokens.dripDuration * 1000.0,
                "blossomDurationMs": HUDMotionTokens.blossomDuration * 1000.0,
                "suctionRetractionMs": HUDMotionTokens.suctionRetractionDuration * 1000.0,
                "reduceMotionMs": HUDMotionTokens.reduceMotionDuration * 1000.0,
                "errorShakeMs": HUDMotionTokens.errorShakeDuration * 1000.0,
                "errorShakeAmplitude": HUDMotionTokens.errorShakeAmplitude,
                "errorShakeCycles": HUDMotionTokens.errorShakeCycles,
                "bargeIsHardCut": true,
                "escapeDismissBudgetMs": HUDMotionTokens.escapeDismissBudget * 1000.0
            ] as [String: Any]
        ]
    }

    /// Export specification metadata for automated test assertions.
    public func getSpecificationSummary() -> [String: Any] {
        let notchInfo = NotchManager.shared.currentNotch()
        return [
            "width": HUDCapsuleView.capsuleWidth,
            "expandedWidth": HUDCapsuleView.expandedWidth,
            "currentWidth": currentWidth,
            "height": HUDCapsuleView.capsuleHeight,
            "notchHeight": currentHeight,
            "cornerRadius": HUDCapsuleView.capsuleRadius,
            "isNonactivatingPanel": panel.styleMask.contains(.nonactivatingPanel),
            "isBorderless": panel.styleMask.contains(.borderless),
            "isFloatingLevel": panel.level == .floating,
            "canJoinAllSpaces": panel.collectionBehavior.contains(.canJoinAllSpaces),
            "fullScreenAuxiliary": panel.collectionBehavior.contains(.fullScreenAuxiliary),
            "ignoresMouseEvents": panel.ignoresMouseEvents,
            "isOpaque": panel.isOpaque,
            "isClearBackground": panel.backgroundColor == .clear,
            "canBecomeKey": panel.canBecomeKey,
            "canBecomeMain": panel.canBecomeMain,
            "hasNotch": notchInfo.hasNotch,
            "notchWidth": notchInfo.notchWidth,
            "transcribedText": transcribedText ?? "",
            "errorShakeSupported": true,
            "isHoverPeekActive": isHoverPeekActive,
            "reduceMotion": NSWorkspace.shared.accessibilityDisplayShouldReduceMotion,
            "maxExpandedHeight": HUDCapsuleView.maxExpandedHeight,
            "labelUsesSingleLineMode": panel.capsuleView.labelField.usesSingleLineMode,
            "labelMaximumNumberOfLines": panel.capsuleView.labelField.maximumNumberOfLines,
            "supportsBreadcrumbs": true,
            "motionTokens": [
                "springStiffness": HUDMotionTokens.springStiffness,
                "springDamping": HUDMotionTokens.springDamping,
                "springMass": HUDMotionTokens.springMass,
                "dripDuration": HUDMotionTokens.dripDuration,
                "blossomDuration": HUDMotionTokens.blossomDuration,
                "stateTransitionDuration": HUDMotionTokens.stateTransitionDuration,
                "suctionRetractionDuration": HUDMotionTokens.suctionRetractionDuration,
                "errorShakeDuration": HUDMotionTokens.errorShakeDuration,
                "errorShakeAmplitude": HUDMotionTokens.errorShakeAmplitude,
                "errorShakeCycles": HUDMotionTokens.errorShakeCycles,
                "reduceMotionDuration": HUDMotionTokens.reduceMotionDuration,
                "escapeDismissDuration": HUDMotionTokens.escapeDismissBudget
            ],
            "notchSpecs": [
                "restingHeight": HUDCapsuleView.notchRestingHeight,
                "listeningHeight": HUDCapsuleView.notchListeningHeight,
                "expandedHeight": HUDCapsuleView.notchExpandedHeight,
                "maxExpandedHeight": HUDCapsuleView.maxExpandedHeight,
                "restingWidth": HUDCapsuleView.capsuleWidth,
                "expandedWidth": HUDCapsuleView.expandedWidth,
                "earFilletRadius": HUDCapsuleView.earFilletRadius,
                "bottomCornerRadius": HUDCapsuleView.bottomCornerRadius,
                "fallbackCornerRadius": HUDCapsuleView.capsuleRadius,
                "hoverPeekHeight": HUDCapsuleView.hoverPeekHeight
            ]
        ]
    }
}
