#!/usr/bin/env bash
# cli/build-cli.sh — write the bin/pet-talk-cli launcher.
#
# Usage: build-cli.sh <output-dir>
#
# `bin/` is not tracked (see .gitignore), and `bin/pet-talk-cli` used to be an
# untracked binary that nothing in the tree built. So after a fresh clone — or
# after anyone cleaned bin/ — the hotkey daemon started with
# "Target CLI: (unresolved)" and Option+Tab was a silent no-op. This script is
# the missing builder: `make build-cli`, and `make build-hotkey` depends on it.
#
# What it writes is a launcher, not a binary: the CLI is Python, and the one
# thing it needs is to be started correctly. `python3 cli/client.py` fails —
# cli/client.py does `from .audio import ...`, which is a relative import with
# no parent package. The module form is required, from the repo root.
#
# No absolute path is baked in. The launcher finds the repo root relative to
# its own location, and picks its interpreter at run time.

set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <output-dir>" >&2
    exit 1
fi

OUT_DIR="$1"
BIN_NAME="pet-talk-cli"
mkdir -p "$OUT_DIR"
TARGET="$OUT_DIR/$BIN_NAME"

cat > "$TARGET" <<'LAUNCHER'
#!/usr/bin/env bash
# GENERATED by cli/build-cli.sh — do not edit here; bin/ is not tracked.
#
# Starts the pet-talk terminal client. The hotkey daemon spawns this on
# Option+Tab (resolution order in cli/hotkey/main.swift: --cli > env
# PET_TALK_CLI_PATH > config.yaml cli_path > sibling of the daemon binary >
# <repo>/bin/pet-talk-cli).
#
# Two things this exists to get right:
#   * cwd is the repo root, and the CLI is started as a MODULE. Running
#     `python3 cli/client.py` raises ImportError — cli/client.py uses a
#     relative import, so it needs its parent package.
#   * the interpreter is one with the audio wheels in it. PET_TALK_PYTHON
#     wins; otherwise the local-ml-py311 conda env (see ~/code/CLAUDE.md —
#     never a fresh venv); otherwise whatever python3 is on PATH, which will
#     work for --help and may not have sounddevice.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PY="${PET_TALK_PYTHON:-}"
if [ -z "$PY" ] || [ ! -x "$PY" ]; then
    PY="$HOME/miniconda3/envs/local-ml-py311/bin/python"
fi
if [ ! -x "$PY" ]; then
    PY="$(command -v python3 2>/dev/null || true)"
fi
if [ -z "$PY" ]; then
    echo "pet-talk-cli: no_python_found — set PET_TALK_PYTHON to an interpreter" >&2
    exit 127
fi

exec "$PY" -m cli.client "$@"
LAUNCHER

chmod +x "$TARGET"
echo "Built: $TARGET"
